// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGjHKrq-H6TpMju4DpRTLixWWQnQCuNWA',
    appId: '1:229607121728:android:0c60e17964cef623',
    messagingSenderId: '229607121728',
    projectId: 'lifeissues-77df5',
    storageBucket: 'lifeissues-77df5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjHKrq-H6TpMju4DpRTLixWWQnQCuNWA',
    appId: '1:229607121728:ios:placeholder',
    messagingSenderId: '229607121728',
    projectId: 'lifeissues-77df5',
    storageBucket: 'lifeissues-77df5.appspot.com',
    iosBundleId: 'com.lifeissues.lifeissues',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjHKrq-H6TpMju4DpRTLixWWQnQCuNWA',
    appId: '1:229607121728:ios:placeholder',
    messagingSenderId: '229607121728',
    projectId: 'lifeissues-77df5',
    storageBucket: 'lifeissues-77df5.appspot.com',
    iosBundleId: 'com.lifeissues.lifeissues',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGjHKrq-H6TpMju4DpRTLixWWQnQCuNWA',
    appId: '1:229607121728:web:placeholder',
    messagingSenderId: '229607121728',
    projectId: 'lifeissues-77df5',
    storageBucket: 'lifeissues-77df5.appspot.com',
    authDomain: 'lifeissues-77df5.firebaseapp.com',
  );
}
